### ISSUE TITLE
Mega responsive article title

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#63]
![image](https://user-images.githubusercontent.com/45851215/107631354-1d0fbf00-6c65-11eb-92e5-01e7a686f1cf.png)

**Comment by filiptronicek** [comment]
This is fixed by setting:
```css
.main__header > h1 {
  word-break: break-word;
}
```
/cc @petrkucerak
